# Uncomment the next line to define a global platform for your project
platform :ios, '13.5'

  target 'iOSSwiftPay' do
  	pod 'Firebase/Analytics'
  	pod 'Firebase/Auth'
  	pod 'Firebase/Core'
  	pod 'Firebase/Firestore'
  end

  target 'iOSSwiftPayTests' do
    use_frameworks!
  	pod 'iOSSnapshotTestCase'
  	pod 'Firebase/Analytics'
  	pod 'Firebase/Auth'
  	pod 'Firebase/Core'
  	pod 'Firebase/Firestore'
  end
